<?php

/**
 * @file
 * Adds support for serializing entities to JSON-LD / Islandora Project.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function private_media_controller_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.hal':
      $output = '';
      return $output;
  }
}

/**
 * Implement hook_form_alter
 */
function private_media_controller_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) : void {
  if ($form_id === "webform_submission_request_access_node_33_add_form") {
    \Drupal::logger('my_module')->error($form_id);
    //print(json_encode($form));
    print_log($form["select_media_to_request"]);
  }
}

if (!function_exists('print_log')) {

  /**
   * Logging in apache log.
   */
  function print_log($thing) {
    error_log(print_r($thing, TRUE), 0);
  }

}

 
